name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: 'self-hosted'

    strategy:
      matrix:
        node-version: [20.10.0]

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
